<?php

use Illuminate\Database\Seeder;

class RateTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('rates')->delete();

        $rates = [
        	[
        		'rateable_id' => 1,
        		'rateable_type' => 'App\Department',
        		'regular' => 39.75,
        		'regular_ot' => 49.69,
        		'regular_nd' => 3.98,
        		'regular_nd_ot' => 4.97,
        		'sun' => 51.68,
        		'sun_ot' => 67.18,
        		'sun_nd' => 5.17,
        		'sun_nd_ot' => 6.72,
        		'spl_holiday' => 51.68,
        		'spl_holiday_ot' => 67.18,
        		'spl_holiday_nd' => 5.17,
        		'spl_holiday_nd_ot' => 6.72,
        		'legal_holiday' => 79.5,
        		'legal_holiday_ot' => 103.35,
        		'legal_holiday_nd' => 7.95,
        		'legal_holiday_nd_ot' => 10.34,
        		'legal_sun' => 99.45,
        		'legal_sun_ot' => 129.285,
        		'legal_sun_nd' => 9.945,
        		'legal_sun_nd_ot' => 12.9285,
        		'no_work_legal_holiday' => 318,
        		'created_at' => \Carbon\Carbon::now(),
        		'updated_at' => \Carbon\Carbon::now(),
        	],
            [
                'rateable_id' => 2,
                'rateable_type' => 'App\Department',
                'regular' => 39.75,
                'regular_ot' => 49.69,
                'regular_nd' => 3.98,
                'regular_nd_ot' => 4.97,
                'sun' => 51.68,
                'sun_ot' => 67.18,
                'sun_nd' => 5.17,
                'sun_nd_ot' => 6.72,
                'spl_holiday' => 51.68,
                'spl_holiday_ot' => 67.18,
                'spl_holiday_nd' => 5.17,
                'spl_holiday_nd_ot' => 6.72,
                'legal_holiday' => 79.5,
                'legal_holiday_ot' => 103.35,
                'legal_holiday_nd' => 7.95,
                'legal_holiday_nd_ot' => 10.34,
                'legal_sun' => 99.45,
                'legal_sun_ot' => 129.285,
                'legal_sun_nd' => 9.945,
                'legal_sun_nd_ot' => 12.9285,
                'no_work_legal_holiday' => 318,
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ],
            [
                'rateable_id' => 3,
                'rateable_type' => 'App\Department',
                'regular' => 39.75,
                'regular_ot' => 49.69,
                'regular_nd' => 3.98,
                'regular_nd_ot' => 4.97,
                'sun' => 51.68,
                'sun_ot' => 67.18,
                'sun_nd' => 5.17,
                'sun_nd_ot' => 6.72,
                'spl_holiday' => 51.68,
                'spl_holiday_ot' => 67.18,
                'spl_holiday_nd' => 5.17,
                'spl_holiday_nd_ot' => 6.72,
                'legal_holiday' => 79.5,
                'legal_holiday_ot' => 103.35,
                'legal_holiday_nd' => 7.95,
                'legal_holiday_nd_ot' => 10.34,
                'legal_sun' => 99.45,
                'legal_sun_ot' => 129.285,
                'legal_sun_nd' => 9.945,
                'legal_sun_nd_ot' => 12.9285,
                'no_work_legal_holiday' => 318,
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ],
            [
                'rateable_id' => 4,
                'rateable_type' => 'App\Department',
                'regular' => 39.75,
                'regular_ot' => 49.69,
                'regular_nd' => 3.98,
                'regular_nd_ot' => 4.97,
                'sun' => 51.68,
                'sun_ot' => 67.18,
                'sun_nd' => 5.17,
                'sun_nd_ot' => 6.72,
                'spl_holiday' => 51.68,
                'spl_holiday_ot' => 67.18,
                'spl_holiday_nd' => 5.17,
                'spl_holiday_nd_ot' => 6.72,
                'legal_holiday' => 79.5,
                'legal_holiday_ot' => 103.35,
                'legal_holiday_nd' => 7.95,
                'legal_holiday_nd_ot' => 10.34,
                'legal_sun' => 99.45,
                'legal_sun_ot' => 129.285,
                'legal_sun_nd' => 9.945,
                'legal_sun_nd_ot' => 12.9285,
                'no_work_legal_holiday' => 318,
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ],
            [
                'rateable_id' => 5,
                'rateable_type' => 'App\Department',
                'regular' => 39.75,
                'regular_ot' => 49.69,
                'regular_nd' => 3.98,
                'regular_nd_ot' => 4.97,
                'sun' => 51.68,
                'sun_ot' => 67.18,
                'sun_nd' => 5.17,
                'sun_nd_ot' => 6.72,
                'spl_holiday' => 51.68,
                'spl_holiday_ot' => 67.18,
                'spl_holiday_nd' => 5.17,
                'spl_holiday_nd_ot' => 6.72,
                'legal_holiday' => 79.5,
                'legal_holiday_ot' => 103.35,
                'legal_holiday_nd' => 7.95,
                'legal_holiday_nd_ot' => 10.34,
                'legal_sun' => 99.45,
                'legal_sun_ot' => 129.285,
                'legal_sun_nd' => 9.945,
                'legal_sun_nd_ot' => 12.9285,
                'no_work_legal_holiday' => 318,
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ],
            [
                'rateable_id' => 6,
                'rateable_type' => 'App\Department',
                'regular' => 39.75,
                'regular_ot' => 49.69,
                'regular_nd' => 3.98,
                'regular_nd_ot' => 4.97,
                'sun' => 51.68,
                'sun_ot' => 67.18,
                'sun_nd' => 5.17,
                'sun_nd_ot' => 6.72,
                'spl_holiday' => 51.68,
                'spl_holiday_ot' => 67.18,
                'spl_holiday_nd' => 5.17,
                'spl_holiday_nd_ot' => 6.72,
                'legal_holiday' => 79.5,
                'legal_holiday_ot' => 103.35,
                'legal_holiday_nd' => 7.95,
                'legal_holiday_nd_ot' => 10.34,
                'legal_sun' => 99.45,
                'legal_sun_ot' => 129.285,
                'legal_sun_nd' => 9.945,
                'legal_sun_nd_ot' => 12.9285,
                'no_work_legal_holiday' => 318,
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ],
            [
                'rateable_id' => 7,
                'rateable_type' => 'App\Department',
                'regular' => 39.75,
                'regular_ot' => 49.69,
                'regular_nd' => 3.98,
                'regular_nd_ot' => 4.97,
                'sun' => 51.68,
                'sun_ot' => 67.18,
                'sun_nd' => 5.17,
                'sun_nd_ot' => 6.72,
                'spl_holiday' => 51.68,
                'spl_holiday_ot' => 67.18,
                'spl_holiday_nd' => 5.17,
                'spl_holiday_nd_ot' => 6.72,
                'legal_holiday' => 79.5,
                'legal_holiday_ot' => 103.35,
                'legal_holiday_nd' => 7.95,
                'legal_holiday_nd_ot' => 10.34,
                'legal_sun' => 99.45,
                'legal_sun_ot' => 129.285,
                'legal_sun_nd' => 9.945,
                'legal_sun_nd_ot' => 12.9285,
                'no_work_legal_holiday' => 318,
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ],
            [
                'rateable_id' => 8,
                'rateable_type' => 'App\Department',
                'regular' => 39.75,
                'regular_ot' => 49.69,
                'regular_nd' => 3.98,
                'regular_nd_ot' => 4.97,
                'sun' => 51.68,
                'sun_ot' => 67.18,
                'sun_nd' => 5.17,
                'sun_nd_ot' => 6.72,
                'spl_holiday' => 51.68,
                'spl_holiday_ot' => 67.18,
                'spl_holiday_nd' => 5.17,
                'spl_holiday_nd_ot' => 6.72,
                'legal_holiday' => 79.5,
                'legal_holiday_ot' => 103.35,
                'legal_holiday_nd' => 7.95,
                'legal_holiday_nd_ot' => 10.34,
                'legal_sun' => 99.45,
                'legal_sun_ot' => 129.285,
                'legal_sun_nd' => 9.945,
                'legal_sun_nd_ot' => 12.9285,
                'no_work_legal_holiday' => 318,
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ]
        ];

        DB::table('rates')->insert($rates);
    }
}
